# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

#=============================================================================
# Target rules for targets named publish-npm

# Build rule for target.
publish-npm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 publish-npm
.PHONY : publish-npm

# fast build rule for target.
publish-npm/fast:
	$(MAKE) $(MAKESILENT) -f bindings/CMakeFiles/publish-npm.dir/build.make bindings/CMakeFiles/publish-npm.dir/build
.PHONY : publish-npm/fast

#=============================================================================
# Target rules for targets named libwhisper

# Build rule for target.
libwhisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libwhisper
.PHONY : libwhisper

# fast build rule for target.
libwhisper/fast:
	$(MAKE) $(MAKESILENT) -f bindings/javascript/CMakeFiles/libwhisper.dir/build.make bindings/javascript/CMakeFiles/libwhisper.dir/build
.PHONY : libwhisper/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/common.dir/build.make examples/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named libmain

# Build rule for target.
libmain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libmain
.PHONY : libmain

# fast build rule for target.
libmain/fast:
	$(MAKE) $(MAKESILENT) -f examples/whisper.wasm/CMakeFiles/libmain.dir/build.make examples/whisper.wasm/CMakeFiles/libmain.dir/build
.PHONY : libmain/fast

#=============================================================================
# Target rules for targets named libstream

# Build rule for target.
libstream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libstream
.PHONY : libstream

# fast build rule for target.
libstream/fast:
	$(MAKE) $(MAKESILENT) -f examples/stream.wasm/CMakeFiles/libstream.dir/build.make examples/stream.wasm/CMakeFiles/libstream.dir/build
.PHONY : libstream/fast

#=============================================================================
# Target rules for targets named libcommand

# Build rule for target.
libcommand: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcommand
.PHONY : libcommand

# fast build rule for target.
libcommand/fast:
	$(MAKE) $(MAKESILENT) -f examples/command.wasm/CMakeFiles/libcommand.dir/build.make examples/command.wasm/CMakeFiles/libcommand.dir/build
.PHONY : libcommand/fast

#=============================================================================
# Target rules for targets named libtalk

# Build rule for target.
libtalk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtalk
.PHONY : libtalk

# fast build rule for target.
libtalk/fast:
	$(MAKE) $(MAKESILENT) -f examples/talk.wasm/CMakeFiles/libtalk.dir/build.make examples/talk.wasm/CMakeFiles/libtalk.dir/build
.PHONY : libtalk/fast

#=============================================================================
# Target rules for targets named libbench

# Build rule for target.
libbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbench
.PHONY : libbench

# fast build rule for target.
libbench/fast:
	$(MAKE) $(MAKESILENT) -f examples/bench.wasm/CMakeFiles/libbench.dir/build.make examples/bench.wasm/CMakeFiles/libbench.dir/build
.PHONY : libbench/fast

ggml-alloc.o: ggml-alloc.c.o
.PHONY : ggml-alloc.o

# target to build an object file
ggml-alloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-alloc.c.o
.PHONY : ggml-alloc.c.o

ggml-alloc.i: ggml-alloc.c.i
.PHONY : ggml-alloc.i

# target to preprocess a source file
ggml-alloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-alloc.c.i
.PHONY : ggml-alloc.c.i

ggml-alloc.s: ggml-alloc.c.s
.PHONY : ggml-alloc.s

# target to generate assembly for a file
ggml-alloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-alloc.c.s
.PHONY : ggml-alloc.c.s

ggml-backend.o: ggml-backend.c.o
.PHONY : ggml-backend.o

# target to build an object file
ggml-backend.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-backend.c.o
.PHONY : ggml-backend.c.o

ggml-backend.i: ggml-backend.c.i
.PHONY : ggml-backend.i

# target to preprocess a source file
ggml-backend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-backend.c.i
.PHONY : ggml-backend.c.i

ggml-backend.s: ggml-backend.c.s
.PHONY : ggml-backend.s

# target to generate assembly for a file
ggml-backend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-backend.c.s
.PHONY : ggml-backend.c.s

ggml-quants.o: ggml-quants.c.o
.PHONY : ggml-quants.o

# target to build an object file
ggml-quants.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-quants.c.o
.PHONY : ggml-quants.c.o

ggml-quants.i: ggml-quants.c.i
.PHONY : ggml-quants.i

# target to preprocess a source file
ggml-quants.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-quants.c.i
.PHONY : ggml-quants.c.i

ggml-quants.s: ggml-quants.c.s
.PHONY : ggml-quants.s

# target to generate assembly for a file
ggml-quants.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml-quants.c.s
.PHONY : ggml-quants.c.s

ggml.o: ggml.c.o
.PHONY : ggml.o

# target to build an object file
ggml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml.c.o
.PHONY : ggml.c.o

ggml.i: ggml.c.i
.PHONY : ggml.i

# target to preprocess a source file
ggml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml.c.i
.PHONY : ggml.c.i

ggml.s: ggml.c.s
.PHONY : ggml.s

# target to generate assembly for a file
ggml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/ggml.c.s
.PHONY : ggml.c.s

whisper.o: whisper.cpp.o
.PHONY : whisper.o

# target to build an object file
whisper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/whisper.cpp.o
.PHONY : whisper.cpp.o

whisper.i: whisper.cpp.i
.PHONY : whisper.i

# target to preprocess a source file
whisper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/whisper.cpp.i
.PHONY : whisper.cpp.i

whisper.s: whisper.cpp.s
.PHONY : whisper.s

# target to generate assembly for a file
whisper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whisper.dir/build.make CMakeFiles/whisper.dir/whisper.cpp.s
.PHONY : whisper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... publish-npm"
	@echo "... common"
	@echo "... libbench"
	@echo "... libcommand"
	@echo "... libmain"
	@echo "... libstream"
	@echo "... libtalk"
	@echo "... libwhisper"
	@echo "... whisper"
	@echo "... ggml-alloc.o"
	@echo "... ggml-alloc.i"
	@echo "... ggml-alloc.s"
	@echo "... ggml-backend.o"
	@echo "... ggml-backend.i"
	@echo "... ggml-backend.s"
	@echo "... ggml-quants.o"
	@echo "... ggml-quants.i"
	@echo "... ggml-quants.s"
	@echo "... ggml.o"
	@echo "... ggml.i"
	@echo "... ggml.s"
	@echo "... whisper.o"
	@echo "... whisper.i"
	@echo "... whisper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

