
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 23.5.0 - arm64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/CheckCSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindThreads.cmake:97 (CHECK_C_SOURCE_COMPILES)"
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "CMakeLists.txt:126 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "/Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles/CMakeScratch/TryCompile-SeoRvO"
      binary: "/Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles/CMakeScratch/TryCompile-SeoRvO"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/cmake/Modules;/Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/cmake/Modules;/Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/cmake/Modules;/Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/cmake/Modules;/Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/cmake/Modules;/Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/cmake/"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles/CMakeScratch/TryCompile-SeoRvO'
        
        Run Build Command(s): /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_a413b/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_a413b.dir/build.make CMakeFiles/cmTC_a413b.dir/build
        Building C object CMakeFiles/cmTC_a413b.dir/src.c.o
        /Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/emcc -DCMAKE_HAVE_LIBC_PTHREAD   -MD -MT CMakeFiles/cmTC_a413b.dir/src.c.o -MF CMakeFiles/cmTC_a413b.dir/src.c.o.d -o CMakeFiles/cmTC_a413b.dir/src.c.o -c /Users/numan/Desktop/tarteel-whisper-to-ggml/whisper.cpp/CMakeFiles/CMakeScratch/TryCompile-SeoRvO/src.c
        Linking C executable cmTC_a413b.js
        /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a413b.dir/link.txt --verbose=1
        /Users/numan/Desktop/emsdk-stuff/emsdk/upstream/emscripten/emcc @CMakeFiles/cmTC_a413b.dir/objects1.rsp -o cmTC_a413b.js 
        
      exitCode: 0
...
