
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 23.5.0 - arm64
...
